name: Actualizar GeoJSON desde Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:     # También se puede ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas geopandas shapely pyproj fiona

      - name: Ejecutar script para actualizar GeoJSON
        run: python Prueba_Agua/untitled2.py

      - name: Configurar git para hacer commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Configurar URL remota con token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Hacer commit y push del GeoJSON
        run: |
          git add sistemas_prueba.geojson
          git commit -m "Actualizar GeoJSON automático" || echo "Sin cambios para commitear"
          git push origin HEAD:main
