name: Actualizar GeoJSON desde Google Sheets

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install pandas geopandas shapely pyproj fiona

      - run: python Prueba_Agua/untitled2.py

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - run: |
          git add sistemas_prueba.geojson
          git commit -m "Actualizar GeoJSON automático" || echo "Sin cambios para commitear"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
